<<<<<<< HEAD
# Author: Avinash Krishna — Team AVV Elites (SIH26153)
=======
>>>>>>> 77949f2bb89fea05df3ee4faf24abd4771ef1671
[pytest]
filterwarnings =
    ignore::sklearn.exceptions.ConvergenceWarning
    ignore::UserWarning:torch.*
testpaths = tests
